'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { activities, constraints, navItems, type Activity } from './data';

type User = { name: string; role: 'Engenharia' | 'Campo' | 'Diretoria' };
type Entry = { id: string; activityId: string; quantity: number; kind: 'Produção' | 'Material' | 'Impedimento'; note: string; status: 'Pendente' | 'Aprovado' | 'Devolvido'; date: string };

const USERS: Record<string,{password:string;user:User}> = {
  'engenharia@planes.demo': { password:'Planes2026!', user:{name:'Mariana Alves',role:'Engenharia'} },
  'campo@planes.demo': { password:'Planes2026!', user:{name:'Carlos Lima',role:'Campo'} },
  'diretoria@planes.demo': { password:'Planes2026!', user:{name:'Ricardo Nunes',role:'Diretoria'} }
};

function Logo({ dark=false }: { dark?: boolean }) {
  return <div className={`brand ${dark?'dark':''}`} aria-label="Planes Engenharia"><span className="brand-mark">P</span><span><strong>PLANES</strong><small>ENGENHARIA INTELIGENTE</small></span></div>;
}

export default function Home() {
  const [user,setUser] = useState<User|null>(null);
  const [email,setEmail] = useState('engenharia@planes.demo');
  const [password,setPassword] = useState('Planes2026!');
  const [loginError,setLoginError] = useState('');
  const [view,setView] = useState('dashboard');
  const [entries,setEntries] = useState<Entry[]>([]);
  const [toast,setToast] = useState('');
  const [mobileMenu,setMobileMenu] = useState(false);

  useEffect(()=>{
    const raw=localStorage.getItem('planes:v1:entries'); if(raw) setEntries(JSON.parse(raw));
    const session=localStorage.getItem('planes:v1:session'); if(session) setUser(JSON.parse(session));
  },[]);
  useEffect(()=>{ if(entries.length) localStorage.setItem('planes:v1:entries',JSON.stringify(entries)); },[entries]);
  function login(e:FormEvent){ e.preventDefault(); const found=USERS[email]; if(!found||found.password!==password){setLoginError('E-mail ou senha inválidos.');return;} setUser(found.user); localStorage.setItem('planes:v1:session',JSON.stringify(found.user)); setView(found.user.role==='Campo'?'field':'dashboard'); }
  function logout(){setUser(null);localStorage.removeItem('planes:v1:session');}
  function notify(message:string){setToast(message);setTimeout(()=>setToast(''),2600)}
  if(!user) return <Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} error={loginError} onSubmit={login}/>;

  const available = navItems.filter(([id]) => user.role!=='Campo' || ['field','weekly','constraints'].includes(id));
  return <div className="app">
    <aside className={mobileMenu?'sidebar open':'sidebar'}>
      <div className="side-brand"><Logo dark/><button className="close-menu" onClick={()=>setMobileMenu(false)}>×</button></div>
      <div className="project-chip"><span>OBRA PILOTO</span><strong>Japaratinga Resort</strong><small>Expansão 3 · Alagoas</small></div>
      <nav>{available.map(([id,label,icon])=><button key={id} onClick={()=>{setView(id);setMobileMenu(false)}} className={view===id?'active':''}><span>{icon}</span>{label}{id==='validation'&&entries.filter(e=>e.status==='Pendente').length>0?<b>{entries.filter(e=>e.status==='Pendente').length}</b>:null}</button>)}</nav>
      <div className="sidebar-foot"><span className="avatar">{user.name.split(' ').map(x=>x[0]).slice(0,2)}</span><div><strong>{user.name}</strong><small>{user.role}</small></div><button onClick={logout} title="Sair">↗</button></div>
    </aside>
    <main>
      <header><button className="menu-button" onClick={()=>setMobileMenu(true)}>☰</button><div><small>PLANES GESTÃO</small><strong>Japaratinga Resort – Expansão 3</strong></div><div className="header-actions"><span className="live-dot">● Dados atualizados</span><button onClick={()=>notify('Central de notificações atualizada')}>♢</button></div></header>
      <section className="content">{renderView(view,{entries,setEntries,notify,user,setView})}</section>
    </main>
    {toast?<div className="toast">✓ {toast}</div>:null}
  </div>;
}

function Login({email,password,setEmail,setPassword,error,onSubmit}:{email:string;password:string;setEmail:(s:string)=>void;setPassword:(s:string)=>void;error:string;onSubmit:(e:FormEvent)=>void}){
  const [show,setShow]=useState(false);
  return <div className="login-page"><div className="login-left"><Logo dark/><div className="login-message"><span>PLATAFORMA DIGITAL DE GESTÃO DE OBRAS</span><h1>Do planejamento<br/>ao canteiro.<br/><em>Do canteiro à decisão.</em></h1><p>Planejamento, execução e inteligência em tempo real para obras de alta performance.</p></div><div className="login-project"><span>OBRA PILOTO</span><strong>Japaratinga Resort – Expansão 3</strong><small>16 frentes monitoradas · Planejamento até nov/2026</small></div></div><div className="login-right"><form onSubmit={onSubmit}><div className="mobile-logo"><Logo/></div><span className="eyebrow">ACESSO RESTRITO</span><h2>Bem-vindo à sua obra</h2><p>Acesse com suas credenciais Planes.</p><label>E-mail corporativo<input aria-label="E-mail corporativo" value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Senha<div className="password"><input aria-label="Senha" value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'}/><button type="button" onClick={()=>setShow(!show)}>{show?'Ocultar':'Mostrar'}</button></div></label>{error?<div className="error">{error}</div>:null}<button className="primary" type="submit">Entrar na plataforma <span>→</span></button><div className="demo"><strong>Acesso de demonstração</strong><span>engenharia@planes.demo</span><span>Senha: Planes2026!</span></div></form></div></div>
}

function renderView(view:string,ctx:{entries:Entry[];setEntries:(x:Entry[])=>void;notify:(s:string)=>void;user:User;setView:(s:string)=>void}){
  if(view==='dashboard') return <Dashboard entries={ctx.entries} setView={ctx.setView}/>;
  if(view==='estrutura') return <Structure/>;
  if(view==='gantt') return <Gantt/>;
  if(view==='balance') return <Balance/>;
  if(view==='lookahead') return <Lookahead notify={ctx.notify}/>;
  if(view==='weekly') return <Weekly/>;
  if(view==='field') return <Field entries={ctx.entries} setEntries={ctx.setEntries} notify={ctx.notify}/>;
  if(view==='validation') return <Validation entries={ctx.entries} setEntries={ctx.setEntries} notify={ctx.notify}/>;
  return <Constraints/>;
}

function PageTitle({kicker,title,children}:{kicker:string;title:string;children?:React.ReactNode}){return <div className="page-title"><div><span>{kicker}</span><h1>{title}</h1></div>{children}</div>}
function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}

function Dashboard({entries,setView}:{entries:Entry[];setView:(s:string)=>void}){
  const approved=entries.filter(e=>e.status==='Aprovado').reduce((s,e)=>s+(e.kind==='Produção'?e.quantity:0),0);
  const metrics=[['Avanço físico','61,8%','Planejado 66,4%','-4,6 p.p.','danger'],['Aderência semanal','78%','18 de 23 compromissos','+6 p.p. vs. semana ant.','success'],['Variação de prazo','+18 dias','Baseline: 30/11/2026','Tendência: 18/12/2026','warning'],['Restrições abertas','12','4 vencidas · 5 críticas','3 liberadas nesta semana','warning']];
  return <><PageTitle kicker="VISÃO EXECUTIVA" title="Painel Planes"><div className="date-filter">Semana 34 · 17–21 ago 2026⌄</div></PageTitle><div className="summary-strip"><div><span>STATUS DA OBRA</span><Badge tone="warning">● Atenção</Badge></div><p>Ritmo abaixo do planejado em <strong>Bloco de Apartamentos</strong> e <strong>Área da Piscina</strong>. Quatro restrições exigem decisão.</p><small>Última consolidação: 21/08/2026 · 17:40</small></div><div className="metric-grid">{metrics.map(m=><article className="metric" key={m[0]}><div><span>{m[0]}</span><i>↗</i></div><strong>{m[1]}</strong><small>{m[2]}</small><footer className={m[4]}>{m[3]}</footer></article>)}</div><div className="dashboard-grid"><article className="panel progress-panel"><div className="panel-title"><div><span>CURVA DE AVANÇO</span><h2>Planejado × realizado</h2></div><Badge>Físico</Badge></div><div className="chart"><div className="axis">100%<br/><br/>75%<br/><br/>50%<br/><br/>25%<br/><br/>0%</div><svg viewBox="0 0 700 230" preserveAspectRatio="none"><path className="gridline" d="M0 45H700M0 95H700M0 145H700M0 195H700"/><path className="planned" d="M0 210 C120 205 120 190 210 178 S350 130 430 108 S570 55 700 25"/><path className="actual" d="M0 210 C120 208 140 195 220 184 S350 148 430 132 S570 92 700 72"/><circle cx="700" cy="72" r="6"/></svg><div className="chart-labels"><span>Mar</span><span>Abr</span><span>Mai</span><span>Jun</span><span>Jul</span><span>Ago</span><span>Set</span><span>Out</span><span>Nov</span></div></div><div className="legend"><span><i className="line planned-line"/>Planejado 66,4%</span><span><i className="line actual-line"/>Realizado 61,8%</span>{approved?<span>+{approved} un. validadas nesta sessão</span>:null}</div></article><article className="panel attention"><div className="panel-title"><div><span>PRIORIDADE</span><h2>Atenções para decisão</h2></div><button onClick={()=>setView('constraints')}>Ver todas →</button></div>{constraints.slice(0,3).map((c,i)=><div className="attention-item" key={c.id}><span className={`priority p${i+1}`}>0{i+1}</span><div><strong>{c.title}</strong><small>{c.area} · Responsável: {c.owner}</small></div><Badge tone={i===0?'danger':'warning'}>{i===0?'Crítica':'Alta'}</Badge></div>)}</article></div><div className="section-head"><div><span>PRODUÇÃO POR FRENTE</span><h2>Onde estamos desviando</h2></div><button onClick={()=>setView('gantt')}>Abrir cronograma completo →</button></div><div className="front-grid">{[['Arena',76,81],['Bloco de apartamentos',54,66],['Infraestrutura',68,72],['Área da piscina',57,69]].map(x=><article className="front" key={x[0] as string}><div><strong>{x[0]}</strong><Badge tone={(x[1] as number)<60?'danger':'warning'}>{(x[1] as number)<60?'Atrasada':'Atenção'}</Badge></div><div className="bar"><i style={{width:`${x[2]}%`}}/><b style={{width:`${x[1]}%`}}/></div><footer><span>Realizado <strong>{x[1]}%</strong></span><span>Planejado {x[2]}%</span></footer></article>)}</div></>
}

function Structure(){const tree=[['Arena',['Quadra coberta','Apoio das quadras','Quadras de tênis','Área 1']],['Bloco de apartamentos',['Torre 1 · Térreo/P1/P2/Rooftop','Torre 2 · Térreo/P1/P2/Rooftop','Torre 3 · Fundações/P1/P2']],['Infraestrutura',['Água','Drenagem','Elétrica','Incêndio','CFTV','Esgoto']],['Recepção e restaurante',['Recepção','Restaurante Trama','SPA e lojas','Guarita']],['Área da piscina',['Piscina','Bares da piscina','Deck seco','Obras em madeira']]];return <><PageTitle kicker="ESTRUTURA ANALÍTICA" title="Estrutura da obra"/><div className="panel tree">{tree.map(([area,children])=><details open key={area as string}><summary><span>▾</span><strong>{area as string}</strong><Badge>{(children as string[]).length} locais</Badge></summary>{(children as string[]).map(c=><div className="tree-child" key={c}><span>└</span>{c}<small>{activities.filter(a=>a.area===area&&a.location.includes(c.split(' · ')[0])).length || 3} atividades</small></div>)}</details>)}</div></>}

function Gantt(){const weeks=['03/08','10/08','17/08','24/08','31/08','07/09'];return <><PageTitle kicker="PLANEJAMENTO MESTRE" title="Cronograma · baseline × atual"><button className="secondary">Filtros ⌄</button></PageTitle><div className="panel gantt"><div className="gantt-head"><strong>Atividade / Local</strong>{weeks.map(w=><span key={w}>{w}</span>)}</div>{activities.slice(4,14).map((a,i)=><div className="gantt-row" key={a.id}><div><strong>{a.name}</strong><small>{a.location} · {a.discipline}</small></div><div className="timeline"><i className="baseline" style={{left:`${(i%4)*9}%`,width:`${32+(i%3)*8}%`}}/><b className={a.status==='Atrasada'?'late':''} style={{left:`${(i%4)*9+3}%`,width:`${Math.max(12,a.progress/2.3)}%`}}/><em style={{left:`${Math.min(86,(i%4)*9+a.progress/2.5)}%`}}>{a.progress}%</em></div></div>)}</div><div className="legend"><span><i className="line baseline-line"/>Baseline</span><span><i className="line current-line"/>Planejamento atual</span><span><i className="late-dot"/>Em atraso</span></div></>}

function Balance(){const rows=['Rooftop','P2','P1','Térreo int.','Térreo ext.','Fundações'];return <><PageTitle kicker="FLUXO DE PRODUÇÃO" title="Linha de balanço"><div className="date-filter">Torres 1–3 · Alvenaria⌄</div></PageTitle><div className="panel balance"><div className="balance-header"><span>LOCALIZAÇÃO</span>{['03 ago','10 ago','17 ago','24 ago','31 ago','07 set'].map(x=><b key={x}>{x}</b>)}</div><div className="balance-body"><div className="locations">{rows.map(r=><span key={r}>{r}</span>)}</div><svg viewBox="0 0 720 360" preserveAspectRatio="none"><path className="balance-grid" d="M0 60H720M0 120H720M0 180H720M0 240H720M0 300H720M120 0V360M240 0V360M360 0V360M480 0V360M600 0V360"/><path className="flow f1" d="M60 330 L190 270 L310 210 L430 150 L560 90 L680 30"/><path className="flow f2" d="M120 330 L255 270 L390 210 L520 150 L660 90"/><path className="flow-real" d="M60 330 L205 270 L345 210 L500 150 L650 110"/><circle cx="650" cy="110" r="7"/></svg></div><div className="legend"><span><i className="line current-line"/>Torre 1 planejado</span><span><i className="line blue-line"/>Torre 2 planejado</span><span><i className="line danger-line"/>Realizado</span></div></div></>}

function Lookahead({notify}:{notify:(s:string)=>void}){const [weeks,setWeeks]=useState(4);const shown=activities.filter(a=>a.status!=='Em dia').slice(0,weeks+2);return <><PageTitle kicker="MÉDIO PRAZO" title="Lookahead"><div className="segmented">{[2,3,4,5,6].map(w=><button className={w===weeks?'active':''} onClick={()=>setWeeks(w)} key={w}>{w} sem.</button>)}</div></PageTitle><div className="lookahead-board">{['17–21 ago','24–28 ago','31 ago–04 set','07–11 set'].slice(0,Math.min(weeks,4)).map((week,wi)=><div className="week-col" key={week}><header><span>SEMANA {34+wi}</span><strong>{week}</strong></header>{shown.filter((_,i)=>i%Math.min(weeks,4)===wi).map(a=><article key={a.id}><div><Badge tone={a.status==='Atrasada'?'danger':'warning'}>{a.status}</Badge><small>{a.area}</small></div><strong>{a.name}</strong><span>{a.location}</span>{constraints.find(c=>c.area===a.area)?<p>△ Restrição vinculada</p>:<p className="ready">✓ Pronta para executar</p>}<button onClick={()=>notify('Atividade promovida para o plano semanal')}>Adicionar ao plano →</button></article>)}</div>)}</div></>}

function Weekly(){return <><PageTitle kicker="COMPROMISSOS" title="Plano semanal"><div className="date-filter">Semana 34 · 17–21 ago⌄</div></PageTitle><div className="weekly-summary"><article><span>ADERÊNCIA</span><strong>78%</strong><small>18 de 23 concluídos</small></article><article><span>EM ANDAMENTO</span><strong>4</strong><small>Dentro da semana</small></article><article><span>NÃO CUMPRIDOS</span><strong>5</strong><small>3 com restrição</small></article></div><div className="panel table"><div className="table-row table-head"><span>Atividade</span><span>Responsável</span><span>Meta</span><span>Realizado</span><span>Situação</span></div>{activities.slice(5,12).map((a,i)=><div className="table-row" key={a.id}><span><strong>{a.name}</strong><small>{a.location}</small></span><span>{i%2?'João Silva':'Equipe Alfa'}</span><span>{a.planned}%</span><span>{a.progress}%</span><span><Badge tone={a.status==='Atrasada'?'danger':a.status==='Em dia'?'success':'warning'}>{a.status}</Badge></span></div>)}</div></>}

function Field({entries,setEntries,notify}:{entries:Entry[];setEntries:(e:Entry[])=>void;notify:(s:string)=>void}){const [mode,setMode]=useState<Entry['kind']|null>(null);const [activityId,setActivityId]=useState(activities[5].id);const [quantity,setQuantity]=useState('');const [note,setNote]=useState('');function submit(e:FormEvent){e.preventDefault();const entry:Entry={id:`entry-${Date.now()}`,activityId,quantity:Number(quantity)||0,kind:mode!,note,status:'Pendente',date:new Date().toLocaleDateString('pt-BR')};setEntries([...entries,entry]);setMode(null);setQuantity('');setNote('');notify('Apontamento enviado para validação')};const today=activities.filter(a=>['Atenção','Atrasada'].includes(a.status)).slice(0,4);return <><PageTitle kicker="CAMPO" title="Minha Obra"><Badge tone="success">● Sincronizado</Badge></PageTitle><div className="field-hero"><div><span>OLÁ, EQUIPE DE CAMPO</span><h2>O que aconteceu na obra hoje?</h2><p>Registre em menos de um minuto.</p></div><div className="field-actions"><button onClick={()=>setMode('Produção')}><i>↗</i><strong>Registrar produção</strong><small>Quantidade executada</small></button><button onClick={()=>setMode('Material')}><i>▣</i><strong>Registrar material</strong><small>Consumo e recebimento</small></button><button onClick={()=>setMode('Impedimento')}><i>△</i><strong>Registrar impedimento</strong><small>Algo bloqueando?</small></button></div></div><div className="section-head"><div><span>SUAS ATIVIDADES</span><h2>Hoje e nesta semana</h2></div><Badge>{today.length} atividades</Badge></div><div className="task-list">{today.map(a=><article key={a.id}><div className="task-status"><i className={a.status==='Atrasada'?'red':'amber'}/><span>{a.status}</span></div><div><strong>{a.name}</strong><small>{a.area} · {a.location}</small></div><div className="mini-progress"><span><i style={{width:`${a.progress}%`}}/></span><b>{a.progress}%</b></div><button onClick={()=>{setActivityId(a.id);setMode('Produção')}}>Apontar →</button></article>)}</div>{mode?<div className="modal"><form onSubmit={submit}><button type="button" className="modal-close" onClick={()=>setMode(null)}>×</button><span className="eyebrow">NOVO APONTAMENTO</span><h2>Registrar {mode.toLowerCase()}</h2><label>Atividade<select value={activityId} onChange={e=>setActivityId(e.target.value)}>{activities.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label>{mode!=='Impedimento'?<label>Quantidade executada<input required min="0.1" step="0.1" value={quantity} onChange={e=>setQuantity(e.target.value)} type="number"/></label>:null}<label>Observação<textarea required={mode==='Impedimento'} value={note} onChange={e=>setNote(e.target.value)} placeholder="Descreva o que aconteceu"/></label><label className="photo-input">Foto da obra<input type="file" accept="image/*"/><span>＋ Adicionar foto</span></label><button className="primary" type="submit">Enviar para validação →</button></form></div>:null}</>}

function Validation({entries,setEntries,notify}:{entries:Entry[];setEntries:(x:Entry[])=>void;notify:(s:string)=>void}){const pending=entries.filter(e=>e.status==='Pendente');function decide(id:string,status:'Aprovado'|'Devolvido'){setEntries(entries.map(e=>e.id===id?{...e,status}:e));notify(status==='Aprovado'?'Apontamento aprovado e indicadores atualizados':'Apontamento devolvido ao campo')}return <><PageTitle kicker="ENGENHARIA" title="Validações"><Badge tone={pending.length?'warning':'success'}>{pending.length} pendentes</Badge></PageTitle>{pending.length===0?<div className="empty"><span>✓</span><h2>Fila de validação em dia</h2><p>Novos apontamentos do campo aparecerão aqui.</p></div>:<div className="validation-list">{pending.map(e=>{const a=activities.find(x=>x.id===e.activityId)!;return <article key={e.id}><div><Badge>{e.kind}</Badge><small>{e.date}</small></div><h3>{a.name}</h3><p>{a.location} · {e.note||'Sem observações'}</p><strong>{e.kind==='Produção'?`${e.quantity} unidades executadas`:'Registro recebido'}</strong><footer><button className="return" onClick={()=>decide(e.id,'Devolvido')}>Devolver</button><button className="approve" onClick={()=>decide(e.id,'Aprovado')}>✓ Aprovar</button></footer></article>})}</div>}</>}

function Constraints(){const [filter,setFilter]=useState('Todas');const list=filter==='Todas'?constraints:constraints.filter(c=>c.status===filter);return <><PageTitle kicker="GESTÃO DE RESTRIÇÕES" title="Restrições"><button className="primary small">＋ Nova restrição</button></PageTitle><div className="filter-row">{['Todas','Vencida','Em tratamento','Aberta'].map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><div className="panel table constraints-table"><div className="table-row table-head"><span>Restrição</span><span>Área</span><span>Responsável</span><span>Prazo</span><span>Situação</span></div>{list.map(c=><div className="table-row" key={c.id}><span><strong>{c.title}</strong><small>{c.type}</small></span><span>{c.area}</span><span>{c.owner}</span><span>{c.due}</span><span><Badge tone={c.status==='Vencida'?'danger':'warning'}>{c.status}</Badge></span></div>)}</div></>}
